name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-express-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: expressserver

      - name: Build server
        run: npm run build --if-present
        working-directory: expressserver

      - name: Test server
        run: npm test
        working-directory: expressserver

  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build client
        run: npm run build --if-present
        working-directory: client

      - name: Test client
        run: npm test
        working-directory: client
